**SIGNATE連携**

In [1]:
!pip install signate

from googleapiclient.discovery import build
import io, os
from googleapiclient.http import MediaIoBaseDownload
from google.colab import auth


auth.authenticate_user()

drive_service = build('drive', 'v3')
results = drive_service.files().list(
        q="name = 'signate.json'", fields="files(id)").execute()
signate_api_key = results.get('files', [])

filename = "/root/.signate/signate.json"
os.makedirs(os.path.dirname(filename), exist_ok=True)

request = drive_service.files().get_media(fileId=signate_api_key[0]['id'])
fh = io.FileIO(filename, 'wb')
downloader = MediaIoBaseDownload(fh, request)
done = False
while done is False:
    status, done = downloader.next_chunk()
    print("Download %d%%." % int(status.progress() * 100))
os.chmod(filename, 600)

     |████████████████████████████████| 138 kB 22.5 MB/s 
  Created wheel for wget: filename=wget-3.2-py3-none-any.whl size=9672 sha256=45a52a9019cbc80a3008f0e17c418bb23b84da857955099b4685964e8e9714f7
  Stored in directory: /root/.cache/pip/wheels/a1/b6/7c/0e63e34eb06634181c63adacca38b79ff8f35c37e3c13e3c02
Successfully built wget
  Attempting uninstall: urllib3
    Found existing installation: urllib3 1.24.3
    Uninstalling urllib3-1.24.3:
      Successfully uninstalled urllib3-1.24.3
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
requests 2.23.0 requires urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1, but you have urllib3 1.26.6 which is incompatible.
datascience 0.10.6 requires folium==0.2.1, but you have folium 0.8.3 which is incompatible.


/usr/local/lib/python3.7/dist-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.26.6) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)


Download 100%.


In [2]:
! signate list

  competitionId  title                                                                                         closing     prize            submitters
---------------  --------------------------------------------------------------------------------------------  ----------  -------------  ------------
              1  【Practice】Bank Marketing                                                                    -                                  5106
             24  【Practice】Boxed Lunch Sales Forecasting                                                     -                                  6278
             27  【Practice】Football Attendance Forecasting                                                   -                                  1429
            100  【練習問題】手書き文字認識                                                                    -           Knowledge               157
            102  【練習問題】タイタニックの生存予測                                                            -           Knowled

In [3]:
! signate files --competition-id=499

  fileId  name                                           title                                                size  updated_at
--------  ---------------------------------------------  ----------------------------------------------  ---------  -------------------
    2219  PBL02_h_exercise4_question.pdf                 PBL02_不良個所自動検出_h.演習④設問                1417656  2021-08-19 15:22:04
    2220  PBL02_i_exercise4_supplementary-documents.pdf  PBL02_不良個所自動検出_i.演習④ガイドコンテンツ     470147  2021-08-19 15:22:07
    2138  train.zip                                      学習用画像データ                                183977509  2021-08-19 15:22:07
    2139  test.zip                                       評価用画像データ                                151304061  2021-08-19 15:22:07
    2140  train_master.tsv                               学習用画像データとラベルIDの対応表                   5221  2021-08-19 15:22:07
    2141  sample_submit.tsv                              応募用サンプルファイル                                100  2021-08-19 15:

In [4]:
! signate download --competition-id=499

sample_submit.tsv

requirements.txt

train_master.tsv

PBL02_sample_code.ipynb

PBL02_i_exercise4_supplementary-documents.pdf

PBL02_h_exercise4_question.pdf

test.zip

train.zip


Download completed.


In [5]:
! unzip train.zip
! unzip test.zip

Archive:  train.zip
   creating: train/
   creating: train/bridge/
  inflating: train/bridge/bridge_000.jpeg  
  inflating: train/bridge/bridge_001.jpeg  
  inflating: train/bridge/bridge_002.jpeg  
  inflating: train/bridge/bridge_003.jpeg  
  inflating: train/bridge/bridge_004.jpeg  
  inflating: train/bridge/bridge_005.jpeg  
  inflating: train/bridge/bridge_006.jpeg  
  inflating: train/bridge/bridge_007.jpeg  
  inflating: train/bridge/bridge_008.jpeg  
  inflating: train/bridge/bridge_009.jpeg  
  inflating: train/bridge/bridge_010.jpeg  
  inflating: train/bridge/bridge_011.jpeg  
  inflating: train/bridge/bridge_012.jpeg  
  inflating: train/bridge/bridge_013.jpeg  
  inflating: train/bridge/bridge_014.jpeg  
  inflating: train/bridge/bridge_015.jpeg  
  inflating: train/bridge/bridge_016.jpeg  
  inflating: train/bridge/bridge_017.jpeg  
  inflating: train/bridge/bridge_018.jpeg  
  inflating: train/bridge/bridge_019.jpeg  
  inflating: train/bridge/bridge_020.jpeg  
  inflati

In [6]:
%ls

adc.json                                       sample_submit.tsv
PBL02_h_exercise4_question.pdf                 test/
PBL02_i_exercise4_supplementary-documents.pdf  test.zip
PBL02_sample_code.ipynb                        train/
requirements.txt                               train_master.tsv
sample_data/                                   train.zip


**コーディングは次のセルから**

# **Import libraries**

In [7]:
!pip install albumentations==0.4.5

     |████████████████████████████████| 116 kB 12.4 MB/s 
     |████████████████████████████████| 631 kB 48.3 MB/s 
  Created wheel for albumentations: filename=albumentations-0.4.5-py3-none-any.whl size=64390 sha256=842523561fe98ecd9f923b3f2d160635f726bac7e951b61840c5d46023ab1839
  Stored in directory: /root/.cache/pip/wheels/8d/23/6e/be83d2d862522484033359805f715261b1f6c4622739a92e06
  Created wheel for imgaug: filename=imgaug-0.2.6-py3-none-any.whl size=654020 sha256=e85d37ee6c7651cfe8302d0c2e018a9f4445acbe8c4778c9a0dc288c206f90f3
  Stored in directory: /root/.cache/pip/wheels/89/72/98/3ebfdba1069a9a8eaaa7ae7265cfd67d63ef0197aaee2e5f9c
Successfully built albumentations imgaug
  Attempting uninstall: imgaug
    Found existing installation: imgaug 0.2.9
    Uninstalling imgaug-0.2.9:
      Successfully uninstalled imgaug-0.2.9
  Attempting uninstall: albumentations
    Found existing installation: albumentations 0.1.12
    Uninstalling albumentations-0.1.12:
      Successfully uninsta

In [8]:
import os
import sys

import torch
import torch.nn as nn
import torch.optim as optim
from torch.optim import lr_scheduler
import torch.nn.functional as F
from torch.optim import Adam, SGD
import torchvision.models as models
from torch.nn.parameter import Parameter
from torch.utils.data import Dataset
from torch.utils.data import DataLoader
from torchvision import transforms

import matplotlib.pyplot as plt
import random
import copy
import numpy as np
import pandas as pd
from sklearn.metrics import f1_score, accuracy_score
from sklearn.preprocessing import LabelEncoder

import cv2

import albumentations as A
from albumentations.pytorch import ToTensorV2
from albumentations import (
    Compose, OneOf, Normalize, CenterCrop, Resize, RandomResizedCrop, RandomCrop, HorizontalFlip, VerticalFlip, 
    RandomBrightness, RandomContrast, RandomBrightnessContrast, RandomRotate90, ShiftScaleRotate, Cutout, 
    IAAAdditiveGaussianNoise, Transpose, HueSaturationValue, CoarseDropout
    )

from tqdm import tqdm
from tqdm.notebook import tqdm

# **CFG**

In [9]:
class CFG:
  DATA_PATH = '/content/'

  TRAIN_PATH = DATA_PATH + 'train/'
  #TRAIN_BRIDGE = TRAIN_PATH + 'bridge/'
  #TRAIN_HORN = TRAIN_PATH + 'horn/'
  #TRAIN_POTATO = TRAIN_PATH + 'potato/'
  #TRAIN_REGULAR = TRAIN_PATH + 'regular/'

  TEST_PATH = DATA_PATH + 'test/'

  TRAIN_TSV = DATA_PATH + 'train_master.tsv'
  SAMPLE_TSV = DATA_PATH + 'sample_submit.tsv'

  IMAGE_SIZE = 32
  BATCH_SIZE = 16
  EPOCH = 10
  CLASS_THRESHOLD = 0.4
  LABELS = ['True','False']
  LR = 5e-4

  DEVICE = 'cuda' if torch.cuda.is_available() else 'cpu'

In [10]:
def to_numpy(tensor):
    """Auxiliary function to convert tensors into numpy arrays
    """
    return tensor.detach().cpu().numpy() if tensor.requires_grad else tensor.cpu().numpy()

# **Preprocessing dataframe**

In [11]:
train_df = pd.read_table(CFG.TRAIN_TSV, sep=',')
train_df

file_name  flag
0     bridge_000.jpeg     1
1     bridge_001.jpeg     1
2     bridge_002.jpeg     1
3     bridge_003.jpeg     1
4     bridge_004.jpeg     1
..                ...   ...
285  regular_095.jpeg     0
286  regular_096.jpeg     0
287  regular_097.jpeg     0
288  regular_098.jpeg     0
289  regular_099.jpeg     0

[290 rows x 2 columns]

In [12]:
flag_df = train_df['flag']
flag_df

0      1
1      1
2      1
3      1
4      1
      ..
285    0
286    0
287    0
288    0
289    0
Name: flag, Length: 290, dtype: int64

In [13]:
#bridgeの個数確認及びbridgeのみデータを一時的なデータフレームとして保存する
train_df[train_df['file_name'].str.startswith('bridge')]
tmp1 = train_df['file_name'][:30]
tmp1

#hornの個数確認及びhornのみデータを一時的なデータフレームとして保存する
train_df[train_df['file_name'].str.startswith('horn')]
tmp2 = train_df['file_name'][30:87]
tmp2

#potatoの個数確認及びpotatoのみデータを一時的なデータフレームとして保存する
train_df[train_df['file_name'].str.startswith('potato')]
tmp3 = train_df['file_name'][87:190]
tmp3

#regularの個数確認及びregularのみデータを一時的なデータフレームとして保存する
train_df[train_df['file_name'].str.startswith('regular')]
tmp4 = train_df['file_name'][190:]
tmp4

190    regular_000.jpeg
191    regular_001.jpeg
192    regular_002.jpeg
193    regular_003.jpeg
194    regular_004.jpeg
             ...       
285    regular_095.jpeg
286    regular_096.jpeg
287    regular_097.jpeg
288    regular_098.jpeg
289    regular_099.jpeg
Name: file_name, Length: 100, dtype: object

In [15]:
#tmp1-4にはそれぞれの状態に応じたデータフレームが入っている
#それぞれに対応するパス'bridge/','horn/','potato/','regular/'を付け加えて、
#全ての画像を一元的に呼び出せるようにする
bridge_df = 'bridge/'+tmp1
horn_df = 'horn/'+tmp2
potato_df = 'potato/'+tmp3
regular_df = 'regular/'+tmp4

#新しくパスを加えたtrain_dfを作る名前はtrain_df2

train_df2 = pd.concat([bridge_df,horn_df,potato_df,regular_df])
train_df2 = pd.concat([train_df2,flag_df], axis=1)
train_df2

file_name  flag
0      bridge/bridge_000.jpeg     1
1      bridge/bridge_001.jpeg     1
2      bridge/bridge_002.jpeg     1
3      bridge/bridge_003.jpeg     1
4      bridge/bridge_004.jpeg     1
..                        ...   ...
285  regular/regular_095.jpeg     0
286  regular/regular_096.jpeg     0
287  regular/regular_097.jpeg     0
288  regular/regular_098.jpeg     0
289  regular/regular_099.jpeg     0

[290 rows x 2 columns]

In [16]:
train_df3 = pd.get_dummies(train_df2, columns=['flag'])
train_df3 = train_df3.rename(columns={'flag_0': 'True'})
train_df3 = train_df3.rename(columns={'flag_1': 'False'})
train_df3

file_name  True  False
0      bridge/bridge_000.jpeg     0      1
1      bridge/bridge_001.jpeg     0      1
2      bridge/bridge_002.jpeg     0      1
3      bridge/bridge_003.jpeg     0      1
4      bridge/bridge_004.jpeg     0      1
..                        ...   ...    ...
285  regular/regular_095.jpeg     1      0
286  regular/regular_096.jpeg     1      0
287  regular/regular_097.jpeg     1      0
288  regular/regular_098.jpeg     1      0
289  regular/regular_099.jpeg     1      0

[290 rows x 3 columns]

In [21]:
test_df = pd.read_table(CFG.SAMPLE_TSV)
test_df

000.jpeg  0
0    001.jpeg  0
1    002.jpeg  0
2    003.jpeg  0
3    004.jpeg  0
4    005.jpeg  0
..        ... ..
207  208.jpeg  0
208  209.jpeg  0
209  210.jpeg  0
210  211.jpeg  0
211  212.jpeg  0

[212 rows x 2 columns]

In [41]:
test_df['000.jpeg'].values

array(['001.jpeg', '002.jpeg', '003.jpeg', '004.jpeg', '005.jpeg',
       '006.jpeg', '007.jpeg', '008.jpeg', '009.jpeg', '010.jpeg',
       '011.jpeg', '012.jpeg', '013.jpeg', '014.jpeg', '015.jpeg',
       '016.jpeg', '017.jpeg', '018.jpeg', '019.jpeg', '020.jpeg',
       '021.jpeg', '022.jpeg', '023.jpeg', '024.jpeg', '025.jpeg',
       '026.jpeg', '027.jpeg', '028.jpeg', '029.jpeg', '030.jpeg',
       '031.jpeg', '032.jpeg', '033.jpeg', '034.jpeg', '035.jpeg',
       '036.jpeg', '037.jpeg', '038.jpeg', '039.jpeg', '040.jpeg',
       '041.jpeg', '042.jpeg', '043.jpeg', '044.jpeg', '045.jpeg',
       '046.jpeg', '047.jpeg', '048.jpeg', '049.jpeg', '050.jpeg',
       '051.jpeg', '052.jpeg', '053.jpeg', '054.jpeg', '055.jpeg',
       '056.jpeg', '057.jpeg', '058.jpeg', '059.jpeg', '060.jpeg',
       '061.jpeg', '062.jpeg', '063.jpeg', '064.jpeg', '065.jpeg',
       '066.jpeg', '067.jpeg', '068.jpeg', '069.jpeg', '070.jpeg',
       '071.jpeg', '072.jpeg', '073.jpeg', '074.jpeg', '075.jp

# **Dataset**

In [47]:
class TestDataset(Dataset):
  def __init__(self, test_df, transform=None):
    self.test_df = test_df
    self.image_names = test_df['000.jpeg'].values
    self.transform = transform

  def __len__(self):
    return len(self.test_df)
  
  def __getitem__(self, idx):
    image_name = self.image_names[idx]
    image_path = CFG.TEST_PATH + image_name
    image = cv2.imread(image_path)
    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

    if self.transform:
      augmented = self.transform(image=image)
      image = augmented['image']
      image.shape
    return {'image':image}

# **Augmentation**

In [30]:
def get_transforms(*,data):
    
    if data == 'tr':
        return Compose([
            A.Resize(CFG.IMAGE_SIZE, CFG.IMAGE_SIZE),
            A.RandomResizedCrop(CFG.IMAGE_SIZE, CFG.IMAGE_SIZE),
            A.HorizontalFlip(p=0.5),
            A.ShiftScaleRotate(p=0.5),
            A.RandomBrightnessContrast(p=0.5),

            A.Normalize(),
            ToTensorV2(),
        ])
    elif data == 'va':
        return Compose([
            Resize(CFG.IMAGE_SIZE, CFG.IMAGE_SIZE),
            Normalize(),
            ToTensorV2(),
        ])

In [73]:
# 上で作成したデータセットクラスを呼び出す
test_dataset = TestDataset(test_df, transform = get_transforms(data = 'va'))
# データセットクラスによって取り出されるデータをbatch数でまとめる
test_loader = DataLoader(test_dataset, CFG.BATCH_SIZE, shuffle = False,drop_last = False, num_workers=2)


In [74]:
test_dataset[0]

{'image': tensor([[[0.9303, 1.1015, 0.9817,  ..., 0.8447, 0.8961, 0.7762],
          [0.9988, 1.0673, 1.1015,  ..., 0.7933, 0.8789, 0.9817],
          [1.0331, 0.9817, 0.9646,  ..., 0.7248, 0.8618, 0.9303],
          ...,
          [0.8104, 1.0331, 0.9303,  ..., 0.4851, 0.5022, 0.4851],
          [0.9303, 0.9303, 0.8961,  ..., 0.5536, 0.4679, 0.4851],
          [1.0502, 0.8276, 0.9817,  ..., 0.4679, 0.5364, 0.5536]],
 
         [[1.1155, 1.2906, 1.1681,  ..., 0.9930, 1.0455, 0.9230],
          [1.1856, 1.2556, 1.2906,  ..., 0.9405, 1.0280, 1.1331],
          [1.2206, 1.1681, 1.1506,  ..., 0.8704, 1.0105, 1.0805],
          ...,
          [0.9755, 1.2206, 1.1155,  ..., 0.6254, 0.6429, 0.6254],
          [1.1155, 1.1155, 1.0805,  ..., 0.6954, 0.6078, 0.6254],
          [1.2381, 1.0105, 1.1681,  ..., 0.6429, 0.6779, 0.6954]],
 
         [[1.3154, 1.4548, 1.3328,  ..., 1.1759, 1.2282, 1.1062],
          [1.3851, 1.4200, 1.4548,  ..., 1.1237, 1.2108, 1.3154],
          [1.3851, 1.3328, 1.31

# **Model**

In [76]:
class Net(nn.Module):
    def __init__(self):
        super().__init__()
        self.conv1 = nn.Conv2d(3, 32, kernel_size=3, padding=1)
        self.conv2 = nn.Conv2d(32, 16, kernel_size=3, padding=1)
        self.fc1 = nn.Linear(16 * 8 * 8, 32)
        self.fc2 = nn.Linear(32, 2)
        
    def forward(self, x):
        out = F.max_pool2d(torch.tanh(self.conv1(x)),2)
        out = F.max_pool2d(torch.tanh(self.conv2(out)), 2)
        out = out.view(-1, 16*8*8)
        out = torch.tanh(self.fc1(out))
        out = self.fc2(out)
        return out
    
model = Net()
model.load_state_dict(torch.load('/content/drive/MyDrive/Colab Notebooks/my_model.pt'))
model = model.to(CFG.DEVICE)


# **Evaluate function**

# **Prediction**

In [77]:
model.eval()

predictions = []
for batch in test_loader:
    image = batch['image'].cuda()
    with torch.no_grad():
        outputs = model(image)
        preds = outputs.argmax(1).detach().cpu().numpy()
        predictions.append(preds)
predictions

[array([0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1]),
 array([0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0]),
 array([1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0]),
 array([1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1]),
 array([1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1]),
 array([1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0]),
 array([1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1]),
 array([1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1]),
 array([0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1]),
 array([0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1]),
 array([0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1]),
 array([1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1]),
 array([1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1]),
 array([1, 0, 1, 1])]

In [78]:
import itertools

pre = list(itertools.chain.from_iterable(predictions))
len(pre)

212

In [84]:
sub_df = pd.read_table(CFG.SAMPLE_TSV)
sub_df['0'] = pre
sub_df

000.jpeg  0
0    001.jpeg  0
1    002.jpeg  1
2    003.jpeg  0
3    004.jpeg  1
4    005.jpeg  1
..        ... ..
207  208.jpeg  1
208  209.jpeg  1
209  210.jpeg  0
210  211.jpeg  1
211  212.jpeg  1

[212 rows x 2 columns]

In [96]:
sub_tsv = sub_df.to_csv(index=False,sep='\t')
sub_tsv

'000.jpeg\t0\n001.jpeg\t0\n002.jpeg\t1\n003.jpeg\t0\n004.jpeg\t1\n005.jpeg\t1\n006.jpeg\t1\n007.jpeg\t0\n008.jpeg\t0\n009.jpeg\t1\n010.jpeg\t0\n011.jpeg\t1\n012.jpeg\t0\n013.jpeg\t1\n014.jpeg\t1\n015.jpeg\t1\n016.jpeg\t1\n017.jpeg\t0\n018.jpeg\t0\n019.jpeg\t1\n020.jpeg\t1\n021.jpeg\t1\n022.jpeg\t0\n023.jpeg\t0\n024.jpeg\t1\n025.jpeg\t1\n026.jpeg\t1\n027.jpeg\t1\n028.jpeg\t0\n029.jpeg\t1\n030.jpeg\t1\n031.jpeg\t0\n032.jpeg\t0\n033.jpeg\t1\n034.jpeg\t1\n035.jpeg\t1\n036.jpeg\t0\n037.jpeg\t1\n038.jpeg\t1\n039.jpeg\t0\n040.jpeg\t1\n041.jpeg\t1\n042.jpeg\t0\n043.jpeg\t1\n044.jpeg\t1\n045.jpeg\t1\n046.jpeg\t1\n047.jpeg\t1\n048.jpeg\t0\n049.jpeg\t1\n050.jpeg\t0\n051.jpeg\t1\n052.jpeg\t1\n053.jpeg\t1\n054.jpeg\t1\n055.jpeg\t1\n056.jpeg\t0\n057.jpeg\t1\n058.jpeg\t0\n059.jpeg\t1\n060.jpeg\t0\n061.jpeg\t1\n062.jpeg\t1\n063.jpeg\t1\n064.jpeg\t1\n065.jpeg\t1\n066.jpeg\t1\n067.jpeg\t1\n068.jpeg\t1\n069.jpeg\t0\n070.jpeg\t0\n071.jpeg\t1\n072.jpeg\t1\n073.jpeg\t1\n074.jpeg\t1\n075.jpeg\t1\n076.jpeg\t0

In [97]:
sub_df.to_csv('mysubmission.tsv', index=False, sep='\t')

In [95]:
df = pd.read_table('/content/mysubmission.tsv', sep=',')
df

001.jpeg\t0
0    002.jpeg\t1
1    003.jpeg\t0
2    004.jpeg\t1
3    005.jpeg\t1
4    006.jpeg\t1
..           ...
206  208.jpeg\t1
207  209.jpeg\t1
208  210.jpeg\t0
209  211.jpeg\t1
210  212.jpeg\t1

[211 rows x 1 columns]